# Nombre de la aplicacion
spring.application.name=api_rest

# Conexion a SQL Server (MimosDemo)
# localhost indica que el contenedor esta exponiendo el puerto en tu maquina
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MimosDemo;encrypt=false
spring.datasource.username=api_mimos_user
spring.datasource.password=MimosDev2026*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate: validate asegura que las tablas existan pero NO las altera ni borra
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Puerto de la API
server.port=8080
